Repository AlejandroCadena-JAC/GymPlanner, pull requests merged in 2023-12, with the labels that each got.

#51 finished firestore adding to collection
  README.md
  app/build.gradle.kts
  app/google-services.json
  app/src/main/java/com/example/workouttracker/MainActivity.kt
  app/src/main/java/com/example/workouttracker/accountpage/SignInPage.kt
  app/src/main/java/com/example/workouttracker/calendar/Calendar.kt
  app/src/main/java/com/example/workouttracker/exerciseinput/ExerciseInput.kt
  app/src/main/java/com/example/workouttracker/notes/NoteInput.kt
  app/src/main/java/com/example/workouttracker/notes/NotesScreen.kt
  build.gradle.kts
Labels: enhancement

#74 App Fixes
  app/build.gradle.kts
  app/google-services.json
  app/src/androidTest/java/com/example/gymplanner/ExampleInstrumentedTest.kt
  app/src/main/java/com/example/gymplanner/LandingScreen.kt
  app/src/main/java/com/example/gymplanner/MainActivity.kt
  app/src/main/java/com/example/gymplanner/accountpage/SignInPage.kt
  app/src/main/java/com/example/gymplanner/accountpage/authentication/UserAuthentication.kt
  app/src/main/java/com/example/gymplanner/calendar/Calendar.kt
  app/src/main/java/com/example/gymplanner/exerciseinput/ExerciseInput.kt
  app/src/main/java/com/example/gymplanner/navbar/ExerciseTabRow.kt
  app/src/main/java/com/example/gymplanner/navbar/WorkoutDestinations.kt
  app/src/main/java/com/example/gymplanner/notes/NoteInput.kt
  app/src/main/java/com/example/gymplanner/notes/NoteItem.kt
  app/src/main/java/com/example/gymplanner/notes/Notes.kt
  app/src/main/java/com/example/gymplanner/notes/NotesList.kt
  app/src/main/java/com/example/gymplanner/notes/NotesScreen.kt
  app/src/main/java/com/example/gymplanner/notes/NotesViewModel.kt
  app/src/main/java/com/example/gymplanner/ui/theme/Color.kt
  app/src/main/java/com/example/gymplanner/ui/theme/Theme.kt
  app/src/main/java/com/example/gymplanner/ui/theme/Type.kt
  app/src/main/java/com/example/workouttracker/exerciseinput/ExerciseInput.kt
  app/src/main/java/com/example/workouttracker/exerciselist/ExerciseList.kt
  app/src/test/java/com/example/gymplanner/ExampleUnitTest.kt
  build.gradle.kts
  settings.gradle.kts
Labels: bug, enhancement, help wanted, ui

#75 App overhaul
  .github/workflows/pull_request-workflow.yml
  LICENSE
  README.md
  app/build.gradle.kts
  app/src/main/java/com/example/gymplanner/MainActivity.kt
  app/src/main/java/com/example/gymplanner/about/AboutUs.kt
  app/src/main/java/com/example/gymplanner/navbar/WorkoutDestinations.kt
  app/src/main/java/com/example/gymplanner/notes/NoteItem.kt
  settings.gradle.kts
Labels: documentation, enhancement

#78 finished calendar
  app/src/main/java/com/example/gymplanner/calendar/Calendar.kt
  app/src/main/java/com/example/gymplanner/notes/NoteInput.kt
  app/src/main/java/com/example/gymplanner/notes/NoteItem.kt
  app/src/main/java/com/example/gymplanner/notes/Notes.kt
Labels: bug, enhancement
